### PR TITLE
Fix rendering paths

### LINKED ISSUE #191: Fix detecting lack of cards in user profile
https://github.com/x-team/unleash/blob/develop/app/views/partials/userpaths.html#L29

We shouldn’t show the "no cards" message if any non-first path contains more than 0 cards.

### LINKED ISSUE #193: New quick cards are being added at the beginning of a path
Instead at the end: https://www.dropbox.com/s/456i61avrvdgst5/Screenshot%202016-06-28%2020.48.38.png?dl=0

### LINKED ISSUE #197: Differences between cards in admin panel and user-side
In the admin panel, "Płytka testująca powiadomienia" is the last one, yet at the user side there are two more being displayed. Also: there is no "path line" in between them.

### PR DESCRIPTION
**Pull request by karolsojko**
Fixes #191 
Fixes #193 
Fixes #197

### CODE REVIEW

File: app/scripts/controllers/user.js [hunk 1]
```diff
@@ -77,15 +77,26 @@ angular.module('unleashApp')
       }
     };
 
+    var filterEmptyPaths = function(paths) {
+      var filteredPaths = [];
+      angular.forEach(paths, function(path) {
```
Comment (theanxy) [inline app/scripts/controllers/user.js]: There are better alternatives for forEach, FYI – http://frontendcollisionblog.com/javascript/2015/08/15/3-reasons-you-should-not-be-using-foreach.html :-)

Comment (karolsojko) [inline app/scripts/controllers/user.js]: Oh - thanks for the tip @theanxy - will try that in the future :) 👍
