### PR TITLE
Fix wrong user #405

### LINKED ISSUE #405: House (of) cards: award goes to a wrong user
Marking a House card as done, sends the #unleash notification as if the achiv was given to the person who marked it, not the House itself: http://d.pr/i/TrSy

### PR DESCRIPTION
**Pull request by karolsojko**
fixes #405 

also fixed #403

### CODE REVIEW

File: app/actions/PathsActions.js [hunk 1]
```diff
@@ -122,7 +122,7 @@ export function pathsUpdateGoal(path, goal, data, slackOptions = {}) {
         if (slackOptions.notifyOnSlack) {
           const notificationParameters = {
             goal: inflatedGoal,
-            user: getState().user.userData,
+            user: getState().profiles.profile,
```
Comment (szymonmichalak) [inline app/actions/PathsActions.js]: By the way you're touching this action, can we get rid of this `getState()`? In my opinion this data should be passed as an argument in this action (from component itself). Redux actions should not use `getState` unless it's really necessary...

**Comment by karolsojko** [comment]
@szymonmichalak updated :)

**Comment by szymonmichalak** [comment]
👍 after fixing tests
